---
- hosts: localhost

  connection: local
  become: vramana
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/ramana/.local/bin"

  vars:
    tools_dir: "/home/ramana/Documents/my-tools"

  roles:
    # - { role: apt }
    # - { role: vim }
    # - { role: rust }
    # - { role: node }
    # - { role: emacs }
    # - { role: go }
    - { role: fonts }


