---
- hosts: localhost

  connection: local
  become: true
  become_method: sudo

  vars:
    tools_dir: "/home/ramana/Documents/my-tools"

  roles:
    - { role: vim }
    # - { role: terminfo, tags: terminfo }
    # - { role: vim, tags: vim }
