---

- name: Download Go
  get_url:
    url: https://dl.google.com/go/go1.11.4.linux-amd64.tar.gz
    dest: /tmp/go1.11.4.linux-amd64.tar.gz
    mode: "0750"

- name: install go
  unarchive:
    src: /tmp/go1.11.4.linux-amd64.tar.gz
    dest: /usr/local/
  become: true
  become_method: sudo


