---

- name: nvim | fetch or update neovim git repo
  git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{tools_dir}}/neovim"

- name: install python neovim client
  pip:
    name: neovim
    extra_args: --user

- name: compile nvim
  make:
    chdir: "{{tools_dir}}/neovim"
    params: CMAKE_BUILD_TYPE=RelWithDebInfo

- name: install nvim
  make:
    chdir: "{{tools_dir}}/neovim"
    target: install
  become: true
  become_method: sudo

